name: Update Flathub on Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Matches v1.0.0, v1.2.3, etc.
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Extract version info
      id: version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        COMMIT_HASH=$(git rev-parse $TAG_NAME)
        VERSION=${TAG_NAME#v}
        
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        echo "📦 Processing release: $TAG_NAME"
        echo "🔍 Commit hash: $COMMIT_HASH"
        echo "📈 Version: $VERSION"

    - name: Check manifest exists
      id: check
      run: |
        MANIFEST_FILE="packaging/io.github.tobagin.tempo.yml"
        
        if [[ ! -f "$MANIFEST_FILE" ]]; then
          echo "❌ Manifest file not found: $MANIFEST_FILE"
          exit 1
        fi
        
        echo "✅ Local manifest found: $MANIFEST_FILE"
        echo "📋 Current manifest tag and commit:"
        grep -A 2 "tag:" "$MANIFEST_FILE" || echo "Tag not found in expected format"
        
        echo "manifest_ready=true" >> $GITHUB_OUTPUT

    - name: Create Flathub PR
      if: steps.check.outputs.manifest_ready == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.FLATHUB_TOKEN }}
      run: |
        FLATHUB_REPO="flathub/io.github.tobagin.tempo"
        
        echo "🔄 Cloning Flathub repository..."
        git clone https://x-access-token:$GITHUB_TOKEN@github.com/$FLATHUB_REPO.git flathub-repo
        cd flathub-repo
        
        git config user.email "action@github.com"
        git config user.name "GitHub Action (Tempo Updates)"
        
        # Copy the updated manifest directly to main
        cp ../packaging/io.github.tobagin.tempo.yml ./io.github.tobagin.tempo.yml
        
        git add io.github.tobagin.tempo.yml
        git commit -m "Update to ${{ steps.version.outputs.tag_name }}

        🚀 **New Release: ${{ steps.version.outputs.tag_name }}**
        
        **Changes:**
        - Updated tag from previous version to ${{ steps.version.outputs.tag_name }}
        - Updated commit hash to ${{ steps.version.outputs.commit_hash }}
        - Automated update from upstream repository
        
        **Source:** https://github.com/tobagin/Tempo/releases/tag/${{ steps.version.outputs.tag_name }}
        
        ---
        *This update was automatically created by GitHub Actions*"
        
        git push https://x-access-token:$GITHUB_TOKEN@github.com/$FLATHUB_REPO.git master
        
        echo "✅ Updated Flathub repository directly: https://github.com/$FLATHUB_REPO"
        echo "🚀 Flathub will automatically build and publish the update"

    - name: Summary
      if: always()
      run: |
        echo "## 📋 Workflow Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Tag:** \`${{ steps.version.outputs.tag_name }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** \`${{ steps.version.outputs.commit_hash }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** \`${{ steps.version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ steps.check.outputs.manifest_ready }}" == "true" ]]; then
          echo "✅ **Manifest Ready:** Local Flatpak manifest found and validated" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Flathub Updated:** Manifest pushed directly to Flathub main branch" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Manifest Missing:** Local manifest not found or invalid" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
        echo "1. Flathub CI will automatically build and test the update" >> $GITHUB_STEP_SUMMARY
        echo "2. If build passes, the new version will be published automatically" >> $GITHUB_STEP_SUMMARY
        echo "3. Monitor at: https://github.com/flathub/io.github.tobagin.tempo" >> $GITHUB_STEP_SUMMARY