name: Update External Data

on:
  schedule:
    - cron: '0 14 * * 1'  # Weekly on Monday at 14:00 UTC
  workflow_dispatch:
    inputs:
      only_check:
        description: 'Only check for updates (do not create PRs)'
        required: false
        default: false
        type: boolean

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tobagin'
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for updates with External Data Checker
      env:
        GIT_AUTHOR_NAME: External Data Checker Bot
        GIT_COMMITTER_NAME: External Data Checker Bot
        GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker run --rm \
          -v "$PWD:/app" \
          -w /app \
          -e GIT_AUTHOR_NAME \
          -e GIT_COMMITTER_NAME \
          -e GIT_AUTHOR_EMAIL \
          -e GIT_COMMITTER_EMAIL \
          -e GITHUB_TOKEN \
          ghcr.io/flathub/flatpak-external-data-checker:latest \
          --update \
          ${{ github.event.inputs.only_check == 'true' && '--dry-run' || '--never-fork' }} \
          packaging/io.github.tobagin.tempo.yml

    - name: Create PR if updates found
      if: github.event.inputs.only_check != 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if git diff --quiet; then
          echo "ℹ️ No updates found"
          exit 0
        fi
        
        echo "🔄 Updates found, creating PR..."
        
        CURRENT_DATE=$(date +"%Y-%m-%d")
        BRANCH_NAME="external-data-update-$CURRENT_DATE"
        
        git checkout -b "$BRANCH_NAME"
        git add -A
        git commit -m "📦 Update external dependencies ($CURRENT_DATE)

        Automated update of external data sources:
        - Checked for new releases and versions
        - Updated manifest with latest available versions
        - Verified source URLs and checksums
        
        Generated by: flatpak-external-data-checker"
        
        git push origin "$BRANCH_NAME"
        
        gh auth login --with-token <<< "$GITHUB_TOKEN"
        
        gh pr create \
          --title "🔄 External Data Update - $CURRENT_DATE" \
          --body "## 🤖 Automated External Data Update

        This PR contains automated updates to external dependencies.

        ### What's Updated
        - ✅ Checked all external data sources in Flatpak manifest  
        - 📦 Updated to latest available versions where found
        - 🔍 Verified source URLs and integrity hashes
        - 📅 Generated on: $CURRENT_DATE

        ### Review Checklist
        - [ ] Verify version numbers are correct
        - [ ] Check that URLs are accessible
        - [ ] Confirm hash/checksum values are accurate  
        - [ ] Test build works with updated dependencies

        ---
        *🤖 This PR was automatically generated by GitHub Actions*" \
          --head "$BRANCH_NAME" \
          --base "main"